#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_LENS_DUMMYLENS_SUPPORT) += mt6592/dummy_lens/
obj-$(CONFIG_MTK_LENS_FM50AF_SUPPORT) += mt6592/fm50af/
obj-$(CONFIG_MTK_LENS_BU6424AF_SUPPORT) += mt6592/bu6424af/
obj-$(CONFIG_MTK_LENS_IMX111AF_SUPPORT) += mt6592/imx111af/
obj-$(CONFIG_MTK_LENS_LC898122AF_SUPPORT) += mt6592/lc898122af/
# obj-y += sensordriver/sensordrive_lens.o

